#pragma once
#ifndef CV_CLASSIFICATION_IDS_H
#define CV_CLASSIFICATION_IDS_H

//
//	CvClassificationIds -- the COMPILE-TIME id table for the json.md par.8/par.9 classification
//	categories. GENERATED by Tools/Migration/curate_classification_ids.py -- do NOT hand-edit;
//	regenerate and commit, exactly like an `_order.json` manifest.
//
//	The ClassificationRegistry SEEDS from this table before minting, so each constant below IS
//	the runtime id and a consumer reads `info.hasSkill(SKILL_BLITZ)` -- ONE parameterized read
//	per domain, never a getter per key ([patterns.md] par. THE GETTER SETUP).
//
//	The categories stay OPEN ([DEC-classification-infos]): a key authored but absent here is still
//	minted at load, appended after the seeded block. Regenerating promotes it to a constant.
//	Nothing serializes -- ids are re-derived per load -- so a regenerated table is save-neutral.
//
//	⛔ The constants carry a reserved CLS_ namespace; the runtime INFOTYPE STRING is still
//	"TAG_MILITARY". The property engine already owns global TagTypes/AttributeTypes in CvEnums.h,
//	and these registries are OPEN, so the namespace makes collision impossible by construction.
//

#include "CvClassificationBlock.h"   // ClsDomain / NUM_CLS_DOMAINS (the seed table's index)

// CLSD_SKILL -- the `skills` block (81 authored keys)
enum SkillClsTypes
{
	CLS_SKILL_ALWAYS_HEAL = 0,
	CLS_SKILL_ALWAYS_HOSTILE = 1,
	CLS_SKILL_ALWAYS_INVISIBLE = 2,
	CLS_SKILL_AMPHIB = 3,
	CLS_SKILL_ANIMAL_IGNORES_BORDERS = 4,
	CLS_SKILL_ASSASSIN = 5,
	CLS_SKILL_ATTACK_ONLY_CITIES = 6,
	CLS_SKILL_BARB_CO_EXIST = 7,
	CLS_SKILL_BLEND_INTO_CITY = 8,
	CLS_SKILL_BLITZ = 9,
	CLS_SKILL_CAN_LEAD_THROUGH_PEAKS = 10,
	CLS_SKILL_CAN_MOVE_ALL_TERRAIN = 11,
	CLS_SKILL_CAN_MOVE_IMPASSABLE = 12,
	CLS_SKILL_CAN_PASS_PEAKS = 13,
	CLS_SKILL_CANNOT_MERGE_SPLIT = 14,
	CLS_SKILL_CELEBRITY = 15,
	CLS_SKILL_COLLATERAL_IMMUNE = 16,
	CLS_SKILL_COUNTER_SPY = 17,
	CLS_SKILL_DCM_FIGHTER_ENGAGE = 18,
	CLS_SKILL_DEFENSE_ONLY = 19,
	CLS_SKILL_DEFENSIVE_VICTORY_MOVE = 20,
	CLS_SKILL_DESTROY = 21,
	CLS_SKILL_ENEMY_ROUTE = 22,
	CLS_SKILL_EXCILE = 23,
	CLS_SKILL_FEATURE_DOUBLE_MOVE = 24,
	CLS_SKILL_FIRST_STRIKE_IMMUNE = 25,
	CLS_SKILL_FLAT_MOVEMENT_COST = 26,
	CLS_SKILL_FLIES_TO_MOVE = 27,
	CLS_SKILL_FOOD = 28,
	CLS_SKILL_FOUND = 29,
	CLS_SKILL_FREE_DROP = 30,
	CLS_SKILL_GATHER_HERD = 31,
	CLS_SKILL_GOLDEN_AGE = 32,
	CLS_SKILL_GREAT_GENERAL = 33,
	CLS_SKILL_HEALS_AS = 34,
	CLS_SKILL_HIDDEN_NATIONALITY = 35,
	CLS_SKILL_HILLS_DOUBLE_MOVE = 36,
	CLS_SKILL_IGNORE_BUILDING_DEFENSE = 37,
	CLS_SKILL_IGNORE_NO_ENTRY_LEVEL = 38,
	CLS_SKILL_IGNORE_TERRAIN_COST = 39,
	CLS_SKILL_IGNORE_ZONE_OF_CONTROL = 40,
	CLS_SKILL_IGNORE_ZONEOF_CONTROL = 41,
	CLS_SKILL_IMMUNE_TO_FIRST_STRIKES = 42,
	CLS_SKILL_INQUISITOR = 43,
	CLS_SKILL_INVESTIGATE = 44,
	CLS_SKILL_MECHANIZED = 45,
	CLS_SKILL_NO_BAD_GOODIES = 46,
	CLS_SKILL_NO_CAPTURE = 47,
	CLS_SKILL_NO_DEFENSIVE_BONUS = 48,
	CLS_SKILL_NO_INVISIBILITY = 49,
	CLS_SKILL_NO_NON_OWNED_CITY_ENTRY = 50,
	CLS_SKILL_NO_NON_TYPE_PROD_MODS = 51,
	CLS_SKILL_NO_SELF_HEAL = 52,
	CLS_SKILL_NUKE_IMMUNE = 53,
	CLS_SKILL_OFFENSIVE_VICTORY_MOVE = 54,
	CLS_SKILL_ONE_UP = 55,
	CLS_SKILL_ONLY_DEFENSIVE = 56,
	CLS_SKILL_ONSLAUGHT = 57,
	CLS_SKILL_PASSAGE = 58,
	CLS_SKILL_PILLAGE = 59,
	CLS_SKILL_PILLAGE_ESPIONAGE = 60,
	CLS_SKILL_PILLAGE_MARAUDER = 61,
	CLS_SKILL_PILLAGE_ON_MOVE = 62,
	CLS_SKILL_PILLAGE_ON_VICTORY = 63,
	CLS_SKILL_PILLAGE_RESEARCH = 64,
	CLS_SKILL_REMOVES_UNIT_COMBATS = 65,
	CLS_SKILL_RENDER_BELOW_WATER = 66,
	CLS_SKILL_RIVAL_TERRITORY = 67,
	CLS_SKILL_RIVER = 68,
	CLS_SKILL_SABOTAGE = 69,
	CLS_SKILL_STAMPEDE = 70,
	CLS_SKILL_STATE_RELIGION = 71,
	CLS_SKILL_STEAL_PLANS = 72,
	CLS_SKILL_STEALTH_DEFENSE = 73,
	CLS_SKILL_SUICIDE = 74,
	CLS_SKILL_TERRAIN_DOUBLE_MOVE = 75,
	CLS_SKILL_TRADABLE = 76,
	CLS_SKILL_UNIT_COMBATS = 77,
	CLS_SKILL_UNLIMITED_EXCEPTION = 78,
	CLS_SKILL_UPGRADE_ANYWHERE = 79,
	CLS_SKILL_ZONE_OF_CONTROL = 80,
	NUM_CLS_SKILL_TYPES = 81
};

// CLSD_TAG -- the `tags` block (54 authored keys)
enum TagClsTypes
{
	CLS_TAG_AIR = 0,
	CLS_TAG_AIR_UNIT = 1,
	CLS_TAG_ANIMAL = 2,
	CLS_TAG_ARCHERY = 3,
	CLS_TAG_ARMORED = 4,
	CLS_TAG_BUREAUCRAT = 5,
	CLS_TAG_CAMOUFLAGE = 6,
	CLS_TAG_CAPTIVE = 7,
	CLS_TAG_CIVILIAN = 8,
	CLS_TAG_COMMANDER = 9,
	CLS_TAG_DIPLOMAT = 10,
	CLS_TAG_DISGUISED = 11,
	CLS_TAG_DOOM = 12,
	CLS_TAG_ENTERTAINER = 13,
	CLS_TAG_FIGHTER = 14,
	CLS_TAG_GUNPOWDER = 15,
	CLS_TAG_HERO = 16,
	CLS_TAG_IDEA = 17,
	CLS_TAG_INVISIBLE = 18,
	CLS_TAG_LAND_UNIT = 19,
	CLS_TAG_MECHANIZED = 20,
	CLS_TAG_MEDIC = 21,
	CLS_TAG_MELEE = 22,
	CLS_TAG_MERCHANT = 23,
	CLS_TAG_MILITARY = 24,
	CLS_TAG_MISSILE = 25,
	CLS_TAG_MISSIONARY = 26,
	CLS_TAG_MOUNTED = 27,
	CLS_TAG_NAVAL = 28,
	CLS_TAG_NAVAL_DISGUISE = 29,
	CLS_TAG_NOMAD = 30,
	CLS_TAG_OUTLAW = 31,
	CLS_TAG_PEOPLE = 32,
	CLS_TAG_POLICE = 33,
	CLS_TAG_POLITICAL = 34,
	CLS_TAG_PRODIGY = 35,
	CLS_TAG_RECON = 36,
	CLS_TAG_SEA_UNIT = 37,
	CLS_TAG_SEAPLANE = 38,
	CLS_TAG_SETTLER = 39,
	CLS_TAG_SIEGE = 40,
	CLS_TAG_SIZE = 41,
	CLS_TAG_SPACE = 42,
	CLS_TAG_SPY = 43,
	CLS_TAG_STEALTH = 44,
	CLS_TAG_SUBMARINE = 45,
	CLS_TAG_SUBMERGED = 46,
	CLS_TAG_SYNTHETIC = 47,
	CLS_TAG_TAMED = 48,
	CLS_TAG_THROWING = 49,
	CLS_TAG_TROOP = 50,
	CLS_TAG_VTOL = 51,
	CLS_TAG_WILD = 52,
	CLS_TAG_WORKER = 53,
	NUM_CLS_TAG_TYPES = 54
};

// CLSD_ATTRIBUTE -- the `attributes` block (4 authored keys)
enum AttributeClsTypes
{
	CLS_ATTRIBUTE_DESTROYED_ON_CAPTURE = 0,
	CLS_ATTRIBUTE_ORBITAL = 1,
	CLS_ATTRIBUTE_ORBITAL_INFRASTRUCTURE = 2,
	CLS_ATTRIBUTE_TEAM_SHARE = 3,
	NUM_CLS_ATTRIBUTE_TYPES = 4
};

// CLSD_AMENITY -- the `amenities` block (11 authored keys)
enum AmenityClsTypes
{
	CLS_AMENITY_ABOLISHED_ANGER = 0,
	CLS_AMENITY_ADDS_3RD_RING = 1,
	CLS_AMENITY_BORDER_OBSTACLE = 2,
	CLS_AMENITY_CAPITAL = 3,
	CLS_AMENITY_FORCE_ALL_TRADE_ROUTES = 4,
	CLS_AMENITY_GOVERNMENT_CENTER = 5,
	CLS_AMENITY_NUKE_IMMUNE = 6,
	CLS_AMENITY_PROTECTED_CULTURE = 7,
	CLS_AMENITY_PROVIDES_FRESH_WATER = 8,
	CLS_AMENITY_PROVIDES_POWER = 9,
	CLS_AMENITY_ZONE_OF_CONTROL = 10,
	NUM_CLS_AMENITY_TYPES = 11
};

// CLSD_CHARACTERISTIC -- the `characteristics` block (9 authored keys)
enum CharacteristicClsTypes
{
	CLS_CHARACTERISTIC_ACTS_AS_CITY = 0,
	CLS_CHARACTERISTIC_BOMBARDABLE = 1,
	CLS_CHARACTERISTIC_COUNTS_AS_PEAK = 2,
	CLS_CHARACTERISTIC_IGNORE_TERRAIN_CULTURE = 3,
	CLS_CHARACTERISTIC_NUKE_IMMUNE = 4,
	CLS_CHARACTERISTIC_PROHIBITS_BONUS = 5,
	CLS_CHARACTERISTIC_UNFOUNDABLE = 6,
	CLS_CHARACTERISTIC_UNIMPROVABLE = 7,
	CLS_CHARACTERISTIC_ZONE_OF_CONTROL = 8,
	NUM_CLS_CHARACTERISTIC_TYPES = 9
};

// CLSD_CAPABILITY -- the `capabilities` block (18 authored keys)
enum CapabilityClsTypes
{
	CLS_CAPABILITY_CAN_BUILD_BRIDGES = 0,
	CLS_CAPABILITY_CAN_FARM_DESERT = 1,
	CLS_CAPABILITY_CAN_FOUND_ON_PEAKS = 2,
	CLS_CAPABILITY_CAN_IGNORE_IRRIGATION = 3,
	CLS_CAPABILITY_CAN_MOVE_FAST_ON_PEAKS = 4,
	CLS_CAPABILITY_CAN_PASS_PEAKS = 5,
	CLS_CAPABILITY_CAN_REBASE_ANYWHERE = 6,
	CLS_CAPABILITY_CAN_SEE_FURTHER_FROM_WATER = 7,
	CLS_CAPABILITY_CAN_SET_CULTURE_RATE = 8,
	CLS_CAPABILITY_CAN_SET_ESPIONAGE_RATE = 9,
	CLS_CAPABILITY_CAN_SET_SCIENCE_RATE = 10,
	CLS_CAPABILITY_CAN_SPREAD_IRRIGATION = 11,
	CLS_CAPABILITY_DCM_AIR_BOMB_1 = 12,
	CLS_CAPABILITY_DCM_AIR_BOMB_2 = 13,
	CLS_CAPABILITY_HAS_CENTERED_MAP = 14,
	CLS_CAPABILITY_HAS_LANGUAGE = 15,
	CLS_CAPABILITY_HAS_RIVER_TRADE = 16,
	CLS_CAPABILITY_HAS_WHOLE_MAP_REVEALED = 17,
	NUM_CLS_CAPABILITY_TYPES = 18
};

// CLSD_POLICY -- the `policies` block (18 authored keys)
enum PolicyClsTypes
{
	CLS_POLICY_ALL_RELIGIONS_ACTIVE = 0,
	CLS_POLICY_ALLOW_INQUISITIONS = 1,
	CLS_POLICY_BANS_NON_STATE_RELIGIONS = 2,
	CLS_POLICY_CAN_DO_ELECTION = 3,
	CLS_POLICY_CITIES_START_WITH_STATE_RELIGION = 4,
	CLS_POLICY_COMMUNISM = 5,
	CLS_POLICY_DISALLOW_INQUISITIONS = 6,
	CLS_POLICY_DRAFTS_ON_CITY_CAPTURE = 7,
	CLS_POLICY_EXTRA_GOODY = 8,
	CLS_POLICY_FIXED_BORDERS = 9,
	CLS_POLICY_MILITARY_FOOD_PRODUCTION = 10,
	CLS_POLICY_NO_CORPORATIONS = 11,
	CLS_POLICY_NO_FOREIGN_CORPORATIONS = 12,
	CLS_POLICY_NO_FOREIGN_TRADE = 13,
	CLS_POLICY_NO_NON_STATE_RELIGION_SPREAD = 14,
	CLS_POLICY_NON_STATE_RELIGION_COMMERCE = 15,
	CLS_POLICY_STATE_RELIGION = 16,
	CLS_POLICY_UPGRADE_ANYWHERE = 17,
	NUM_CLS_POLICY_TYPES = 18
};

// The seed table -- ClassificationRegistry::buildAndResolve mints these first, in order, so the
// constants above equal the runtime ids. One NULL-terminated list per domain, indexed by ClsDomain.
static const char* const CLS_SEED_CLSD_SKILL[] =
{
	"alwaysHeal",
	"alwaysHostile",
	"alwaysInvisible",
	"amphib",
	"animalIgnoresBorders",
	"assassin",
	"attackOnlyCities",
	"barbCoExist",
	"blendIntoCity",
	"blitz",
	"canLeadThroughPeaks",
	"canMoveAllTerrain",
	"canMoveImpassable",
	"canPassPeaks",
	"cannotMergeSplit",
	"celebrity",
	"collateralImmune",
	"counterSpy",
	"dcmFighterEngage",
	"defenseOnly",
	"defensiveVictoryMove",
	"destroy",
	"enemyRoute",
	"excile",
	"featureDoubleMove",
	"firstStrikeImmune",
	"flatMovementCost",
	"fliesToMove",
	"food",
	"found",
	"freeDrop",
	"gatherHerd",
	"goldenAge",
	"greatGeneral",
	"healsAs",
	"hiddenNationality",
	"hillsDoubleMove",
	"ignoreBuildingDefense",
	"ignoreNoEntryLevel",
	"ignoreTerrainCost",
	"ignoreZoneOfControl",
	"ignoreZoneofControl",
	"immuneToFirstStrikes",
	"inquisitor",
	"investigate",
	"mechanized",
	"noBadGoodies",
	"noCapture",
	"noDefensiveBonus",
	"noInvisibility",
	"noNonOwnedCityEntry",
	"noNonTypeProdMods",
	"noSelfHeal",
	"nukeImmune",
	"offensiveVictoryMove",
	"oneUp",
	"onlyDefensive",
	"onslaught",
	"passage",
	"pillage",
	"pillageEspionage",
	"pillageMarauder",
	"pillageOnMove",
	"pillageOnVictory",
	"pillageResearch",
	"removesUnitCombats",
	"renderBelowWater",
	"rivalTerritory",
	"river",
	"sabotage",
	"stampede",
	"stateReligion",
	"stealPlans",
	"stealthDefense",
	"suicide",
	"terrainDoubleMove",
	"tradable",
	"unitCombats",
	"unlimitedException",
	"upgradeAnywhere",
	"zoneOfControl",
	NULL
};

static const char* const CLS_SEED_CLSD_TAG[] =
{
	"air",
	"airUnit",
	"animal",
	"archery",
	"armored",
	"bureaucrat",
	"camouflage",
	"captive",
	"civilian",
	"commander",
	"diplomat",
	"disguised",
	"doom",
	"entertainer",
	"fighter",
	"gunpowder",
	"hero",
	"idea",
	"invisible",
	"landUnit",
	"mechanized",
	"medic",
	"melee",
	"merchant",
	"military",
	"missile",
	"missionary",
	"mounted",
	"naval",
	"navalDisguise",
	"nomad",
	"outlaw",
	"people",
	"police",
	"political",
	"prodigy",
	"recon",
	"seaUnit",
	"seaplane",
	"settler",
	"siege",
	"size",
	"space",
	"spy",
	"stealth",
	"submarine",
	"submerged",
	"synthetic",
	"tamed",
	"throwing",
	"troop",
	"vtol",
	"wild",
	"worker",
	NULL
};

static const char* const CLS_SEED_CLSD_ATTRIBUTE[] =
{
	"destroyedOnCapture",
	"orbital",
	"orbitalInfrastructure",
	"teamShare",
	NULL
};

static const char* const CLS_SEED_CLSD_AMENITY[] =
{
	"abolishedAnger",
	"adds3rdRing",
	"borderObstacle",
	"capital",
	"forceAllTradeRoutes",
	"governmentCenter",
	"nukeImmune",
	"protectedCulture",
	"providesFreshWater",
	"providesPower",
	"zoneOfControl",
	NULL
};

static const char* const CLS_SEED_CLSD_CHARACTERISTIC[] =
{
	"actsAsCity",
	"bombardable",
	"countsAsPeak",
	"ignoreTerrainCulture",
	"nukeImmune",
	"prohibitsBonus",
	"unfoundable",
	"unimprovable",
	"zoneOfControl",
	NULL
};

static const char* const CLS_SEED_CLSD_CAPABILITY[] =
{
	"canBuildBridges",
	"canFarmDesert",
	"canFoundOnPeaks",
	"canIgnoreIrrigation",
	"canMoveFastOnPeaks",
	"canPassPeaks",
	"canRebaseAnywhere",
	"canSeeFurtherFromWater",
	"canSetCultureRate",
	"canSetEspionageRate",
	"canSetScienceRate",
	"canSpreadIrrigation",
	"dcmAirBomb1",
	"dcmAirBomb2",
	"hasCenteredMap",
	"hasLanguage",
	"hasRiverTrade",
	"hasWholeMapRevealed",
	NULL
};

static const char* const CLS_SEED_CLSD_POLICY[] =
{
	"allReligionsActive",
	"allowInquisitions",
	"bansNonStateReligions",
	"canDoElection",
	"citiesStartWithStateReligion",
	"communism",
	"disallowInquisitions",
	"draftsOnCityCapture",
	"extraGoody",
	"fixedBorders",
	"militaryFoodProduction",
	"noCorporations",
	"noForeignCorporations",
	"noForeignTrade",
	"noNonStateReligionSpread",
	"nonStateReligionCommerce",
	"stateReligion",
	"upgradeAnywhere",
	NULL
};

static const char* const* const CLS_SEED_KEYS[NUM_CLS_DOMAINS] =
{
	CLS_SEED_CLSD_SKILL,
	CLS_SEED_CLSD_TAG,
	CLS_SEED_CLSD_ATTRIBUTE,
	CLS_SEED_CLSD_AMENITY,
	CLS_SEED_CLSD_CHARACTERISTIC,
	CLS_SEED_CLSD_CAPABILITY,
	CLS_SEED_CLSD_POLICY,
};

#endif // CV_CLASSIFICATION_IDS_H
