#include "CvGameCoreDLL.h"
#include "CvJsonBuildingInfo.h"
#include "CvJsonUnitCombatInfo.h"
#include "CvInfos.h"

//
// Python interface for info classes (formerly structs)
// These are simple enough to be exposed directly - no wrappers
//

void CyInfoPythonInterface1()
{
	OutputDebugString("Python Extension Module - CyInfoPythonInterface1\n");

	python::class_<CvInfoBase>("CvInfoBase", python::no_init)

		.def("isGraphicalOnly", &CvInfoBase::isGraphicalOnly, "bool ()")

		.def("getType", &CvInfoBase::getType, "string ()")
		.def("getButton", &CvInfoBase::getButton, "string ()")

		.def("getTextKey", &CvInfoBase::pyGetTextKey, "wstring ()")
		.def("getText", &CvInfoBase::pyGetText, "wstring ()")
		.def("getDescription", &CvInfoBase::pyGetDescription, "wstring ()")
		.def("getDescriptionForm", &CvInfoBase::pyGetDescriptionForm, "wstring ()")
		.def("getCivilopedia", &CvInfoBase::pyGetCivilopedia, "wstring ()")
		.def("getStrategy", &CvInfoBase::pyGetStrategy, "wstring ()")
		.def("getHelp", &CvInfoBase::pyGetHelp, "wstring ()")
		;

	python::class_<CvHotkeyInfo, python::bases<CvInfoBase> >("CvHotkeyInfo", python::no_init)
		.def("getHotKeyVal", &CvHotkeyInfo::getHotKeyVal)
		.def("getHotKeyString", &CvHotkeyInfo::pyGetHotKeyString)
		.def("isAltDown", &CvHotkeyInfo::isAltDown)
		.def("isShiftDown", &CvHotkeyInfo::isShiftDown)
		.def("isCtrlDown", &CvMapInfo::isCtrlDown)
	;

	python::class_<CvScalableInfo>("CvScalableInfo", python::no_init)
		.def("getScale", &CvScalableInfo::getScale, "float ()")
		;

	python::class_<CvJsonSpecialistInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvSpecialistInfo", python::no_init)

		.def("getGreatPeopleUnitType", &CvJsonSpecialistInfo::getGreatPeopleUnitType, "int ()")
		.def("getGreatPeopleRateChange", &CvJsonSpecialistInfo::getGreatPeopleRateChange, "int ()")
		.def("getMissionType", &CvJsonSpecialistInfo::getMissionType, "int ()")

		.def("isVisible", &CvJsonSpecialistInfo::isVisible, "bool ()")
		.def("isSlave", &CvJsonSpecialistInfo::isSlave, "bool ()")

		.def("getYieldChange", &CvJsonSpecialistInfo::getYieldChange, "int (int i)")
		.def("getCommerceChange", &CvJsonSpecialistInfo::getCommerceChange, "int (int i)")
		.def("getExperience", &CvJsonSpecialistInfo::getExperience, "int ()")
		.def("getFlavorValue", &CvJsonSpecialistInfo::getFlavorValue, "int (int i)")

		.def("getTexture", &CvJsonSpecialistInfo::getTexture, "string ()")
	;

	python::class_<CvJsonTechInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvTechInfo", python::no_init)
		.def("getAdvisorType", &CvJsonTechInfo::getAdvisorType, "int ()")
		.def("getResearchCost", &CvJsonTechInfo::getResearchCost, "int ()")
		.def("getEra", &CvJsonTechInfo::getEra, "int ()")
		.def("getTradeRoutes", &CvJsonTechInfo::getTradeRoutes, "int ()")
		.def("getFeatureProductionModifier", &CvJsonTechInfo::getFeatureProductionModifier, "int ()")
		.def("getWorkerSpeedModifier", &CvJsonTechInfo::getWorkerSpeedModifier, "int ()")
		.def("getFirstFreeUnit", &CvJsonTechInfo::getFirstFreeUnit, "int ()")
		.def("getHealth", &CvJsonTechInfo::getHealth, "int ()")
		.def("getHappiness", &CvJsonTechInfo::getHappiness, "int ()")
		.def("getFirstFreeTechs", &CvJsonTechInfo::getFirstFreeTechs, "int ()")
		.def("getPowerValue", &CvJsonTechInfo::getPowerValue, "int ()")

		.def("getGridX", &CvJsonTechInfo::getGridX, "int ()")
		.def("getGridY", &CvJsonTechInfo::getGridY, "int ()")

		.def("isGlobal", &CvJsonTechInfo::isGlobal, "bool ()")
		.def("isRepeat", &CvJsonTechInfo::isRepeat, "bool ()")
		.def("isTrade", &CvJsonTechInfo::isTrade, "bool ()")
		.def("isDisable", &CvJsonTechInfo::isDisable, "bool ()")
		.def("isGoodyTech", &CvJsonTechInfo::isGoodyTech, "bool ()")
		.def("isExtraWaterSeeFrom", &CvJsonTechInfo::isExtraWaterSeeFrom, "bool ()")
		.def("isMapCentering", &CvJsonTechInfo::isMapCentering, "bool ()")
		.def("isMapVisible", &CvJsonTechInfo::isMapVisible, "bool ()")
		.def("isMapTrading", &CvJsonTechInfo::isMapTrading, "bool ()")
		.def("isTechTrading", &CvJsonTechInfo::isTechTrading, "bool ()")
		.def("isGoldTrading", &CvJsonTechInfo::isGoldTrading, "bool ()")
		.def("isOpenBordersTrading", &CvJsonTechInfo::isOpenBordersTrading, "bool ()")
		.def("isDefensivePactTrading", &CvJsonTechInfo::isDefensivePactTrading, "bool ()")
		.def("isPermanentAllianceTrading", &CvJsonTechInfo::isPermanentAllianceTrading, "bool ()")
		.def("isVassalStateTrading", &CvJsonTechInfo::isVassalStateTrading, "bool ()")
		.def("isBridgeBuilding", &CvJsonTechInfo::isBridgeBuilding, "bool ()")
		.def("isIrrigation", &CvJsonTechInfo::isIrrigation, "bool ()")
		.def("isIgnoreIrrigation", &CvJsonTechInfo::isIgnoreIrrigation, "bool ()")
		.def("isWaterWork", &CvJsonTechInfo::isWaterWork, "bool ()")
		.def("isRiverTrade", &CvJsonTechInfo::isRiverTrade, "bool ()")

		.def("getQuote", &CvJsonTechInfo::getQuote, "wstring ()")
		.def("getSound", &CvJsonTechInfo::getSound, "string ()")

		.def("getDomainExtraMoves", &CvJsonTechInfo::getDomainExtraMoves, "int (int i)")
		.def("getFlavorValue", &CvJsonTechInfo::getFlavorValue, "int (int i)")
		.def("getPrereqOrTechs", &CvJsonTechInfo::getPrereqOrTechs, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqAndTechs", &CvJsonTechInfo::getPrereqAndTechs, python::return_value_policy<python::reference_existing_object>())
		.def("getNumLeadsToTechs", &CvJsonTechInfo::getNumLeadsToTechs, "int ()")
		.def("getLeadsToTech", &CvJsonTechInfo::getLeadsToTech, "int (int i)")

		.def("isCommerceFlexible", &CvJsonTechInfo::isCommerceFlexible, "bool (int i)")
		.def("isTerrainTrade", &CvJsonTechInfo::isTerrainTrade, "bool (int i)")

		.def("getNumPrereqBuildings", &CvJsonTechInfo::getNumPrereqBuildings, "int ()")
		.def("getPrereqBuildingType", &CvJsonTechInfo::getPrereqBuildingType, "int (int i)")
		.def("getPrereqBuildingMinimumRequired", &CvJsonTechInfo::getPrereqBuildingMinimumRequired, "int (int i)")
		.def("getNumPrereqOrBuildings", &CvJsonTechInfo::getNumPrereqOrBuildings, "int ()")
		.def("getPrereqOrBuildingType", &CvJsonTechInfo::getPrereqOrBuildingType, "int (int i)")
		.def("getPrereqOrBuildingMinimumRequired", &CvJsonTechInfo::getPrereqOrBuildingMinimumRequired, "int (int i)")
		;

	python::class_<CvJsonPromotionInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvPromotionInfo", python::no_init)

		.def("getPrereqPromotion", &CvJsonPromotionInfo::getPrereqPromotion, "int ()")
		.def("getPrereqOrPromotion1", &CvJsonPromotionInfo::getPrereqOrPromotion1, "int ()")
		.def("getPrereqOrPromotion2", &CvJsonPromotionInfo::getPrereqOrPromotion2, "int ()")
		.def("getActionInfoIndex", &CvJsonPromotionInfo::getActionInfoIndex, "int ()")

		.def("getTechPrereq", &CvJsonPromotionInfo::getTechPrereq, "int ()")
		.def("getStateReligionPrereq", &CvJsonPromotionInfo::getStateReligionPrereq, "int ()")
		.def("getVisibilityChange", &CvJsonPromotionInfo::getVisibilityChange, "int ()")
		.def("getMoveDiscountChange", &CvJsonPromotionInfo::getMoveDiscountChange, "int ()")
		.def("getWithdrawalChange", &CvJsonPromotionInfo::getWithdrawalChange, "int ()")
		.def("getCollateralDamageChange", &CvJsonPromotionInfo::getCollateralDamageChange, "int ()")
		.def("getFirstStrikesChange", &CvJsonPromotionInfo::getFirstStrikesChange, "int ()")
		.def("getChanceFirstStrikesChange", &CvJsonPromotionInfo::getChanceFirstStrikesChange, "int ()")
		.def("getEnemyHealChange", &CvJsonPromotionInfo::getEnemyHealChange, "int ()")
		.def("getNeutralHealChange", &CvJsonPromotionInfo::getNeutralHealChange, "int ()")
		.def("getFriendlyHealChange", &CvJsonPromotionInfo::getFriendlyHealChange, "int ()")
		.def("getCombatPercent", &CvJsonPromotionInfo::getCombatPercent, "int ()")
		.def("getCityAttackPercent", &CvJsonPromotionInfo::getCityAttackPercent, "int ()")
		.def("getCityDefensePercent", &CvJsonPromotionInfo::getCityDefensePercent, "int ()")
		.def("getHillsDefensePercent", &CvJsonPromotionInfo::getHillsDefensePercent, "int ()")
		.def("getCommandType", &CvJsonPromotionInfo::getCommandType, "int ()")
		.def("getRevoltProtection", &CvJsonPromotionInfo::getRevoltProtection, "int ()")
		.def("getPillageChange", &CvJsonPromotionInfo::getPillageChange, "int ()")
		.def("getUpgradeDiscount", &CvJsonPromotionInfo::getUpgradeDiscount, "int ()")

		.def("isLeader", &CvJsonPromotionInfo::isLeader, "bool ()")
		.def("isRiver", &CvJsonPromotionInfo::isRiver, "bool ()")

		.def("getObsoleteTech", &CvJsonPromotionInfo::getObsoleteTech, "int ()")

		.def("getSound", &CvJsonPromotionInfo::getSound, "string ()")

		// Arrays

		.def("getTerrainDefensePercent", &CvJsonPromotionInfo::getTerrainDefensePercent, "int (int i)")
		.def("getFeatureDefensePercent", &CvJsonPromotionInfo::getFeatureDefensePercent, "int (int i)")

		.def("getUnitCombat", &CvJsonPromotionInfo::getUnitCombat, "bool (int i)")
		.def("getPromotionLine", &CvJsonPromotionInfo::getPromotionLine, "int ()")

		.def("getNumQualifiedUnitCombatTypes", &CvJsonPromotionInfo::getNumQualifiedUnitCombatTypes, "int ()")
		.def("getQualifiedUnitCombatType", &CvJsonPromotionInfo::getQualifiedUnitCombatType, "int (int i)")
		.def("getNumDisqualifiedUnitCombatTypes", &CvJsonPromotionInfo::getNumDisqualifiedUnitCombatTypes, "int ()")
		.def("getDisqualifiedUnitCombatType", &CvJsonPromotionInfo::getDisqualifiedUnitCombatType, "int (int i)")

		.def("isStatus", &CvJsonPromotionInfo::isStatus, "bool ()")
		//.def("isAffliction", &CvJsonPromotionInfo::isAffliction, "bool ()")

		.def("getAddsBuildType", &CvJsonPromotionInfo::getAddsBuildType, "int (int i)")
		.def("getNumAddsBuildTypes", &CvJsonPromotionInfo::getNumAddsBuildTypes, "int ()")
		;

	python::class_<CvMissionInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvMissionInfo", python::no_init)
		.def("getTime", &CvMissionInfo::getTime, "int ()")

		.def("isSound", &CvMissionInfo::isSound, "bool ()")
		.def("isTarget", &CvMissionInfo::isTarget, "bool ()")
		.def("isBuild", &CvMissionInfo::isBuild, "bool ()")
		.def("getVisible", &CvMissionInfo::getVisible, "bool ()")
		;

	python::class_<CvActionInfo, boost::noncopyable>("CvActionInfo", python::no_init)
		.def("getButton", &CvActionInfo::getButton, "string ()")
		;

	python::class_<CvJsonUnitInfo, python::bases<CvInfoBase, CvScalableInfo>, boost::noncopyable>("CvUnitInfo", python::no_init)
		.def("getAdvisorType", &CvJsonUnitInfo::getAdvisorType, "int ()")

		.def("getMaxGlobalInstances", &CvJsonUnitInfo::getMaxGlobalInstances, "int ()")
		.def("getMaxPlayerInstances", &CvJsonUnitInfo::getMaxPlayerInstances, "int ()")
		.def("getProductionCost", &CvJsonUnitInfo::getProductionCost, "int ()")
		.def("getMinAreaSize", &CvJsonUnitInfo::getMinAreaSize, "int ()")
		.def("getMoves", &CvJsonUnitInfo::getMoves, "int ()")
		.def("getAirRange", &CvJsonUnitInfo::getAirRange, "int ()")
		.def("getWorkRate", &CvJsonUnitInfo::getWorkRate, "int ()")
		.def("getGreatWorkCulture", &CvJsonUnitInfo::getGreatWorkCulture, "int ()")
		.def("getEspionagePoints", &CvJsonUnitInfo::getEspionagePoints, "int ()")
		.def("getCombat", &CvJsonUnitInfo::getCombat, "int ()")
		.def("getAirCombat", &CvJsonUnitInfo::getAirCombat, "int ()")
		.def("getFirstStrikes", &CvJsonUnitInfo::getFirstStrikes, "int ()")
		.def("getChanceFirstStrikes", &CvJsonUnitInfo::getChanceFirstStrikes, "int ()")
		.def("getCollateralDamage", &CvJsonUnitInfo::getCollateralDamage, "int ()")

		.def("getCargoSpace", &CvJsonUnitInfo::getCargoSpace, "int ()")
		.def("getConscriptionValue", &CvJsonUnitInfo::getConscriptionValue, "int ()")
		.def("getPowerValue", &CvJsonUnitInfo::getPowerValue, "int ()")
		.def("getSpecialUnitType", &CvJsonUnitInfo::getSpecialUnitType, "int ()")
		.def("getUnitCaptureType", &CvJsonUnitInfo::getUnitCaptureType, "int ()")
		.def("getUnitCombatType", &CvJsonUnitInfo::getUnitCombatType, "int ()")
		.def("getDomainType", &CvJsonUnitInfo::getDomainType, "int ()")
		.def("getDefaultUnitAIType", &CvJsonUnitInfo::getDefaultUnitAIType, "int ()")
		.def("getAdvisorType", &CvJsonUnitInfo::getAdvisorType, "int ()")

		.def("getObsoleteTech", &CvJsonUnitInfo::getObsoleteTech, "int ()")
		.def("isStateReligion", &CvJsonUnitInfo::isStateReligion, "bool ()")

		.def("getHolyCity", &CvJsonUnitInfo::getHolyCity, "int ()")
		.def("getReligionType", &CvJsonUnitInfo::getReligionType, "int ()")
		.def("getStateReligion", &CvJsonUnitInfo::getStateReligion, "int ()")
		.def("getPrereqReligion", &CvJsonUnitInfo::getPrereqReligion, "int ()")
		.def("getPrereqCorporation", &CvJsonUnitInfo::getPrereqCorporation, "int ()")
		.def("getPrereqOrBuildingsNum", &CvJsonUnitInfo::getPrereqOrBuildingsNum, "int ()")
		.def("getPrereqOrBuilding", &CvJsonUnitInfo::getPrereqOrBuilding, "int (int)")
		.def("getPrereqAndTech", &CvJsonUnitInfo::getPrereqAndTech, "int ()")
		.def("getPrereqAndBonus", &CvJsonUnitInfo::getPrereqAndBonus, "int ()")
		.def("getNumUnitNames", &CvJsonUnitInfo::getNumUnitNames, "int ()")
		.def("getCommandType", &CvJsonUnitInfo::getCommandType, "int ()")

		.def("isFoodProduction", &CvJsonUnitInfo::isFoodProduction, "bool ()")
		.def("isOnlyDefensive", &CvJsonUnitInfo::isOnlyDefensive, "bool ()")
		.def("isMilitaryProduction", &CvJsonUnitInfo::isMilitaryProduction, "bool ()")
		.def("isSpy", &CvJsonUnitInfo::isSpy, "bool ()")
		.def("isInvestigate", &CvJsonUnitInfo::isInvestigate, "bool ()")
		.def("isFound", &CvJsonUnitInfo::isFound, "bool ()")
		.def("isGoldenAge", &CvJsonUnitInfo::isGoldenAge, "bool ()")
		.def("isInvisible", &CvJsonUnitInfo::isInvisible, "bool ()")
		.def("isIgnoreBuildingDefense", &CvJsonUnitInfo::isIgnoreBuildingDefense, "bool ()")
		.def("isNukeImmune", &CvJsonUnitInfo::isNukeImmune, "bool ()")
		.def("isHiddenNationality", &CvJsonUnitInfo::isHiddenNationality, "bool ()")

		// Arrays
		.def("getPrereqAndTechs", &CvJsonUnitInfo::getPrereqAndTechs, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqOrBonuses", &CvJsonUnitInfo::getPrereqOrBonuses, python::return_value_policy<python::reference_existing_object>())
		.def("getFlavorValue", &CvJsonUnitInfo::getFlavorValue, "int (int i)")
		.def("getBonusProductionModifier", &CvJsonUnitInfo::getBonusProductionModifier, "int (int i)")

		.def("isPrereqOrCivics", &CvJsonUnitInfo::isPrereqOrCivics, "bool (int i)")

		.def("getPrereqAndBuilding", &CvJsonUnitInfo::getPrereqAndBuilding, "int (int i)")
		.def("getNumPrereqAndBuildings", &CvJsonUnitInfo::getNumPrereqAndBuildings, "int ()")

		.def("getUnitUpgrade", &CvJsonUnitInfo::getUnitUpgrade, "int (int i)")
		.def("getNumUnitUpgrades", &CvJsonUnitInfo::getNumUnitUpgrades, "int ()")
		.def("getUnitAIType", &CvJsonUnitInfo::getUnitAIType, "bool (int i)")
		.def("getBuild", &CvJsonUnitInfo::getBuild, "int (int i)")
		.def("getNumBuilds", &CvJsonUnitInfo::getNumBuilds, "short ()")
		.def("hasBuild", &CvJsonUnitInfo::hasBuild, "bool (BuildTypes eBuild)")
		.def("getReligionSpreads", &CvJsonUnitInfo::getReligionSpreads, "int (int i)")
		.def("getCorporationSpreads", &CvJsonUnitInfo::getCorporationSpreads, "int (int i)")
		.def("getGreatPeoples", &CvJsonUnitInfo::getGreatPeoples, "bool (int i)")
		.def("getBuildings", &CvJsonUnitInfo::getBuildings, "int (int i)")
		.def("getHasBuilding", &CvJsonUnitInfo::getHasBuilding, "bool (int i)")
		.def("getNumBuildings", &CvJsonUnitInfo::getNumBuildings, "int ()")
		.def("getNumHeritage", &CvJsonUnitInfo::getNumHeritage, "int ()")
		.def("getHeritage", &CvJsonUnitInfo::getHeritage, "int ()")
		.def("getFreePromotions", &CvJsonUnitInfo::getFreePromotions, "bool (int i)")
		//.def("getTerrainImpassable", &CvJsonUnitInfo::getTerrainImpassable, "bool (int i)")
		//.def("getFeatureImpassable", &CvJsonUnitInfo::getFeatureImpassable, "bool (int i)")
		.def("getUnitNames", &CvJsonUnitInfo::getUnitNames, "string (int i)")
		.def("getArtInfo", &CvJsonUnitInfo::getArtInfo,  python::return_value_policy<python::reference_existing_object>(), "CvArtInfoUnit* (int i, bool bLate)")
		//TB SubCombat Mod begin  TB Combat Mods Begin
		//boolean vectors
		.def("isSubCombatType", &CvJsonUnitInfo::isSubCombatType, "int (int i)")
		.def("isQualifiedPromotionType", &CvJsonUnitInfo::isQualifiedPromotionType, "bool (int i)")
		.def("hasUnitCombat", &CvJsonUnitInfo::hasUnitCombat, "bool (UnitCombatTypes eUnitCombat)")
		.def("getTotalModifiedCombatStrength100", &CvJsonUnitInfo::getTotalModifiedCombatStrength100, "int (bool bSizeMatters)")
		//TB Combat Mods End  TB SubCombat Mod end

		.def("getMapCategories", &CvJsonUnitInfo::getMapCategories, python::return_value_policy<python::reference_existing_object>())

		.def("getTrainCondition", &CvJsonUnitInfo::getTrainCondition, python::return_value_policy<python::reference_existing_object>())
		;

	python::class_<CvSpecialUnitInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvSpecialUnitInfo", python::no_init)
		.def("isValid", &CvSpecialUnitInfo::isValid, "bool ()")
		;

	python::class_<CvJsonCivicOptionInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvCivicOptionInfo", python::no_init)
		//.def("getTraitNoUpkeep", &CvJsonCivicOptionInfo::getTraitNoUpkeep, "bool (int i)")
		;

	python::class_<CvJsonCivicInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvCivicInfo", python::no_init)

		.def("getCivicOptionType", &CvJsonCivicInfo::getCivicOptionType, "int ()")
		.def("getUpkeep", &CvJsonCivicInfo::getUpkeep, "int ()")
		.def("getGreatPeopleRateModifier", &CvJsonCivicInfo::getGreatPeopleRateModifier, "int ()")
		.def("getGreatGeneralRateModifier", &CvJsonCivicInfo::getGreatGeneralRateModifier, "int ()")
		.def("getExtraHealth", &CvJsonCivicInfo::getExtraHealth, "int ()")
		.def("getFreeExperience", &CvJsonCivicInfo::getFreeExperience, "int ()")
		.def("getWorkerSpeedModifier", &CvJsonCivicInfo::getWorkerSpeedModifier, "int ()")
		.def("getMilitaryProductionModifier", &CvJsonCivicInfo::getMilitaryProductionModifier, "int ()")
		.def("getWarWearinessModifier", &CvJsonCivicInfo::getWarWearinessModifier, "int ()")
		.def("getFreeSpecialist", &CvJsonCivicInfo::getFreeSpecialist, "int ()")
		.def("getTradeRoutes", &CvJsonCivicInfo::getTradeRoutes, "int ()")
		.def("getTechPrereq", &CvJsonCivicInfo::getTechPrereq, "int ()")
		.def("getStateReligionHappiness", &CvJsonCivicInfo::getStateReligionHappiness, "int ()")
		.def("getStateReligionUnitProductionModifier", &CvJsonCivicInfo::getStateReligionUnitProductionModifier, "int ()")
		.def("getStateReligionBuildingProductionModifier", &CvJsonCivicInfo::getStateReligionBuildingProductionModifier, "int ()")
		.def("getStateReligionFreeExperience", &CvJsonCivicInfo::getStateReligionFreeExperience, "int ()")

		.def("getRevIdxLocal", &CvJsonCivicInfo::getRevIdxLocal, "int ()")
		.def("getRevIdxNational", &CvJsonCivicInfo::getRevIdxNational, "int ()")
		.def("getRevIdxHolyCityGood", &CvJsonCivicInfo::getRevIdxHolyCityGood, "int ()")
		.def("getRevIdxHolyCityBad", &CvJsonCivicInfo::getRevIdxHolyCityBad, "int ()")
		.def("getRevIdxSwitchTo", &CvJsonCivicInfo::getRevIdxSwitchTo, "int ()")
		.def("getRevIdxNationalityMod", &CvJsonCivicInfo::getRevIdxNationalityMod, "float ()")
		.def("getRevIdxBadReligionMod", &CvJsonCivicInfo::getRevIdxBadReligionMod, "float ()")
		.def("getRevIdxGoodReligionMod", &CvJsonCivicInfo::getRevIdxGoodReligionMod, "float ()")
		.def("getRevViolentMod", &CvJsonCivicInfo::getRevViolentMod, "float ()")
		.def("getRevReligiousFreedom", &CvJsonCivicInfo::getRevReligiousFreedom, "int ()")
		.def("getRevLaborFreedom", &CvJsonCivicInfo::getRevLaborFreedom, "int ()")
		.def("getRevEnvironmentalProtection", &CvJsonCivicInfo::getRevEnvironmentalProtection, "int ()")
		.def("getRevDemocracyLevel", &CvJsonCivicInfo::getRevDemocracyLevel, "int ()")

		.def("isCommunism", &CvJsonCivicInfo::isCommunism, "bool ()")
		.def("isFreeSpeech", &CvJsonCivicInfo::isFreeSpeech, "bool ()")
		.def("isCanDoElection", &CvJsonCivicInfo::isCanDoElection, "bool ()")

		.def("isBuildingOnlyHealthy", &CvJsonCivicInfo::isBuildingOnlyHealthy, "bool ()")
		.def("isStateReligion", &CvJsonCivicInfo::isStateReligion, "bool ()")
		.def("isAnyImprovementYieldChange", &CvJsonCivicInfo::isAnyImprovementYieldChange, "bool ()")
		.def("isAnyBuildingHappinessChange", &CvJsonCivicInfo::isAnyBuildingHappinessChange, "bool ()")
		.def("isAnyBuildingHealthChange", &CvJsonCivicInfo::isAnyBuildingHealthChange, "bool ()")

		// Arrays

		.def("getYieldModifier", &CvJsonCivicInfo::getYieldModifier, "int (int i)")
		.def("getCommerceModifier", &CvJsonCivicInfo::getCommerceModifier, "int (int i)")
		.def("getSpecialistExtraCommerce", &CvJsonCivicInfo::getSpecialistExtraCommerce, "int (int i)")
		.def("getBuildingHappinessChanges", &CvJsonCivicInfo::getBuildingHappinessChanges, "int (int i)")
		.def("getBuildingHealthChanges", &CvJsonCivicInfo::getBuildingHealthChanges, "int (int i)")
		.def("getBuildingProductionModifier", &CvJsonCivicInfo::getBuildingProductionModifier, "int (int i)")
		.def("getBuildingCommerceModifier", &CvJsonCivicInfo::getBuildingCommerceModifier, "int (int i, int j)")

		.def("isSpecialistValid", &CvJsonCivicInfo::isSpecialistValid, "bool (int i)")
		.def("getImprovementYieldChanges", &CvJsonCivicInfo::getImprovementYieldChanges, "int (int i, int j)")
		.def("getFlavorValue", &CvJsonCivicInfo::getFlavorValue, "int (int i)")
		;

	python::class_<CvJsonBuildingInfo, python::bases<CvInfoBase, CvScalableInfo>, boost::noncopyable>("CvBuildingInfo", python::no_init)

		.def("getMaxGlobalInstances", &CvJsonBuildingInfo::getMaxGlobalInstances, "int ()")
		.def("getMaxTeamInstances", &CvJsonBuildingInfo::getMaxTeamInstances, "int ()")
		.def("getMaxPlayerInstances", &CvJsonBuildingInfo::getMaxPlayerInstances, "int ()")
		.def("isNoLimit", &CvJsonBuildingInfo::isNoLimit, "bool ()")
		.def("getVictoryThreshold", &CvJsonBuildingInfo::getVictoryThreshold, "int (int i)")

		.def("getVictoryPrereq", &CvJsonBuildingInfo::getVictoryPrereq, "int ()")
		.def("getObsoleteTech", &CvJsonBuildingInfo::getObsoleteTech, "int ()")
		.def("getPrereqAndTech", &CvJsonBuildingInfo::getPrereqAndTech, "int ()")
		.def("getFreeBonuses", &CvJsonBuildingInfo::getFreeBonuses, python::return_value_policy<python::reference_existing_object>())
		.def("getFreeBuilding", &CvJsonBuildingInfo::getFreeBuilding, "int ()")
		.def("getFreeAreaBuilding", &CvJsonBuildingInfo::getFreeAreaBuilding, "int ()")
		.def("getCivic", &CvJsonBuildingInfo::getCivicOption, "int ()")
		.def("getProductionCost", &CvJsonBuildingInfo::getProductionCost, "int ()")
		.def("getMinAreaSize", &CvJsonBuildingInfo::getMinAreaSize, "int ()")
		.def("getPrereqPopulation", &CvJsonBuildingInfo::getPrereqPopulation, "int ()")
		.def("getNumCitiesPrereq", &CvJsonBuildingInfo::getNumCitiesPrereq, "int ()")
		.def("getNumTeamsPrereq", &CvJsonBuildingInfo::getNumTeamsPrereq, "int ()")
		.def("getUnitLevelPrereq", &CvJsonBuildingInfo::getUnitLevelPrereq, "int ()")
		.def("getMinLatitude", &CvJsonBuildingInfo::getMinLatitude, "int ()")
		.def("getMaxLatitude", &CvJsonBuildingInfo::getMaxLatitude, "int ()")
		.def("getGreatPeopleRateModifier", &CvJsonBuildingInfo::getGreatPeopleRateModifier, "int ()")
		.def("getGreatGeneralRateModifier", &CvJsonBuildingInfo::getGreatGeneralRateModifier, "int ()")
		.def("getAnarchyModifier", &CvJsonBuildingInfo::getAnarchyModifier, "int ()")
		.def("getGoldenAgeModifier", &CvJsonBuildingInfo::getGoldenAgeModifier, "int ()")
		.def("getFreeExperience", &CvJsonBuildingInfo::getFreeExperience, "int ()")
		.def("getGlobalFreeExperience", &CvJsonBuildingInfo::getGlobalFreeExperience, "int ()")
		.def("getFoodKept", &CvJsonBuildingInfo::getFoodKept, "int ()")
		.def("getPopulationgrowthratepercentage", &CvJsonBuildingInfo::getPopulationgrowthratepercentage, "int ()")
		.def("getAirModifier", &CvJsonBuildingInfo::getAirModifier, "int ()")
		.def("getNukeModifier", &CvJsonBuildingInfo::getNukeModifier, "int ()")
		.def("getFreeSpecialist", &CvJsonBuildingInfo::getFreeSpecialist, "int ()")
		.def("getAreaFreeSpecialist", &CvJsonBuildingInfo::getAreaFreeSpecialist, "int ()")
		.def("getGlobalFreeSpecialist", &CvJsonBuildingInfo::getGlobalFreeSpecialist, "int ()")
		.def("getHappiness", &CvJsonBuildingInfo::getHappiness, "int ()")
		.def("getHappinessPercentPerPopulation", &CvJsonBuildingInfo::getHappinessPercentPerPopulation, "int ()")
		.def("getStateReligionHappiness", &CvJsonBuildingInfo::getStateReligionHappiness, "int ()")
		.def("getWorkerSpeedModifier", &CvJsonBuildingInfo::getWorkerSpeedModifier, "int ()")
		.def("getMilitaryProductionModifier", &CvJsonBuildingInfo::getMilitaryProductionModifier, "int ()")
		.def("getSpaceProductionModifier", &CvJsonBuildingInfo::getSpaceProductionModifier, "int ()")
		.def("getTradeRoutes", &CvJsonBuildingInfo::getTradeRoutes, "int ()")
		.def("getCoastalTradeRoutes", &CvJsonBuildingInfo::getCoastalTradeRoutes, "int ()")
		.def("getGlobalTradeRoutes", &CvJsonBuildingInfo::getGlobalTradeRoutes, "int ()")
		.def("getTradeRouteModifier", &CvJsonBuildingInfo::getTradeRouteModifier, "int ()")
		.def("getForeignTradeRouteModifier", &CvJsonBuildingInfo::getForeignTradeRouteModifier, "int ()")
		.def("getPowerValue", &CvJsonBuildingInfo::getPowerValue, "int ()")
		.def("getSpecialBuildingType", &CvJsonBuildingInfo::getSpecialBuilding)
		.def("getAdvisorType", &CvJsonBuildingInfo::getAdvisorType, "int ()")
		.def("getHolyCity", &CvJsonBuildingInfo::getHolyCity, "int ()")
		.def("getReligionType", &CvJsonBuildingInfo::getReligionType, "int ()")
		.def("getPrereqStateReligion", &CvJsonBuildingInfo::getPrereqStateReligion, "int ()")
		.def("getPrereqReligion", &CvJsonBuildingInfo::getPrereqReligion, "int ()")
		.def("getPrereqCorporation", &CvJsonBuildingInfo::getPrereqCorporation, "int ()")
		.def("getFoundsCorporation", &CvJsonBuildingInfo::getFoundsCorporation, "int ()")
		.def("getGlobalReligionCommerce", &CvJsonBuildingInfo::getGlobalReligionCommerce, "int ()")
		.def("getPrereqAndBonus", &CvJsonBuildingInfo::getPrereqAndBonus, "int ()")
		.def("getGreatPeopleUnitType", &CvJsonBuildingInfo::getGreatPeopleUnitType, "int ()")
		.def("getGreatPeopleRateChange", &CvJsonBuildingInfo::getGreatPeopleRateChange, "int ()")
		.def("getMaintenanceModifier", &CvJsonBuildingInfo::getMaintenanceModifier, "int ()")
		.def("getWarWearinessModifier", &CvJsonBuildingInfo::getWarWearinessModifier, "int ()")
		.def("getGlobalWarWearinessModifier", &CvJsonBuildingInfo::getGlobalWarWearinessModifier, "int ()")
		.def("getEnemyWarWearinessModifier", &CvJsonBuildingInfo::getEnemyWarWearinessModifier, "int ()")
		.def("getHealth", &CvJsonBuildingInfo::getHealth, "int ()")
		.def("getHealthPercentPerPopulation", &CvJsonBuildingInfo::getHealthPercentPerPopulation, "int ()")
		.def("getGlobalHealth", &CvJsonBuildingInfo::getGlobalHealth, "int ()")
		.def("getAllCityDefenseModifier", &CvJsonBuildingInfo::getAllCityDefenseModifier, "int ()")
		.def("getBombardDefenseModifier", &CvJsonBuildingInfo::getBombardDefenseModifier, "int ()")
		.def("getBuildingDefenseRecoverySpeedModifier", &CvJsonBuildingInfo::getBuildingDefenseRecoverySpeedModifier, "int ()")
		.def("getCityDefenseRecoverySpeedModifier", &CvJsonBuildingInfo::getCityDefenseRecoverySpeedModifier, "int ()")
		.def("getDefenseModifier", &CvJsonBuildingInfo::getDefenseModifier, "int ()")
		.def("getEspionageDefenseModifier", &CvJsonBuildingInfo::getEspionageDefenseModifier, "int ()")
		.def("getLocalDynamicDefense", &CvJsonBuildingInfo::getLocalDynamicDefense, "int ()")
		.def("getMinDefense", &CvJsonBuildingInfo::getMinDefense, "int ()")
		.def("getNoEntryDefenseLevel", &CvJsonBuildingInfo::getNoEntryDefenseLevel, "int ()")
		.def("getRiverDefensePenalty", &CvJsonBuildingInfo::getRiverDefensePenalty, "int ()")
		.def("getRevIdxLocal", &CvJsonBuildingInfo::getRevIdxLocal, "int ()")
		.def("getRevIdxNational", &CvJsonBuildingInfo::getRevIdxNational, "int ()")
		.def("getMissionType", &CvJsonBuildingInfo::getMissionType, "int ()")
		.def("getVoteSourceType", &CvJsonBuildingInfo::getVoteSourceType, "int ()")
		.def("getPrereqVicinityBonus", &CvJsonBuildingInfo::getPrereqVicinityBonus, "int ()")
		.def("getPrereqRawVicinityBonus", &CvJsonBuildingInfo::getPrereqRawVicinityBonus, "int ()")
		.def("getHurryCostModifier", &CvJsonBuildingInfo::getHurryCostModifier, "int ()")
		.def("getHurryAngerModifier", &CvJsonBuildingInfo::getHurryAngerModifier, "int ()")
		.def("getObsoletesToBuilding", &CvJsonBuildingInfo::getObsoletesToBuilding, "int ()")
		.def("getAdjacentDamagePercent", &CvJsonBuildingInfo::getAdjacentDamagePercent, "int ()")
		.def("getLineOfSight", &CvJsonBuildingInfo::getLineOfSight, "int ()")
		.def("getAirUnitCapacity", &CvJsonBuildingInfo::getAirUnitCapacity, "int ()")
		.def("getAirlift", &CvJsonBuildingInfo::getAirlift, "int ()")
		.def("getAreaHappiness", &CvJsonBuildingInfo::getAreaHappiness, "int ()")
		.def("getAreaHealth", &CvJsonBuildingInfo::getAreaHealth, "int ()")
		.def("getDamageAttackerChance", &CvJsonBuildingInfo::getDamageAttackerChance, "int ()")
		.def("getDamageToAttacker", &CvJsonBuildingInfo::getDamageToAttacker, "int ()")
		.def("getDistanceMaintenanceModifier", &CvJsonBuildingInfo::getDistanceMaintenanceModifier, "int ()")
		.def("getDomesticGreatGeneralRateModifier", &CvJsonBuildingInfo::getDomesticGreatGeneralRateModifier, "int ()")
		.def("getGlobalGreatPeopleRateModifier", &CvJsonBuildingInfo::getGlobalGreatPeopleRateModifier, "int ()")
		.def("getGlobalHappiness", &CvJsonBuildingInfo::getGlobalHappiness, "int ()")
		.def("getGlobalMaintenanceModifier", &CvJsonBuildingInfo::getGlobalMaintenanceModifier, "int ()")
		.def("getGlobalPopulationChange", &CvJsonBuildingInfo::getGlobalPopulationChange, "int ()")
		.def("getGlobalSpaceProductionModifier", &CvJsonBuildingInfo::getGlobalSpaceProductionModifier, "int ()")
		.def("getHealRateChange", &CvJsonBuildingInfo::getHealRateChange, "int ()")
		.def("getInsidiousness", &CvJsonBuildingInfo::getInsidiousness, "int ()")
		.def("getInvestigation", &CvJsonBuildingInfo::getInvestigation, "int ()")
		.def("getNationalCaptureProbabilityModifier", &CvJsonBuildingInfo::getNationalCaptureProbabilityModifier, "int ()")
		.def("getNationalCaptureResistanceModifier", &CvJsonBuildingInfo::getNationalCaptureResistanceModifier, "int ()")
		.def("getNumUnitFullHeal", &CvJsonBuildingInfo::getNumUnitFullHeal, "int ()")
		.def("getUnitUpgradePriceModifier", &CvJsonBuildingInfo::getUnitUpgradePriceModifier, "int ()")

		.def("isAutoBuild", &CvJsonBuildingInfo::isAutoBuild, "bool ()")
		.def("isWater", &CvJsonBuildingInfo::isWater, "bool ()")
		.def("isRiver", &CvJsonBuildingInfo::isRiver, "bool ()")
		.def("isProvidesFreshWater", &CvJsonBuildingInfo::isProvidesFreshWater, "bool ()")
		.def("isFreshWater", &CvJsonBuildingInfo::isFreshWater, "bool ()")
		.def("isPower", &CvJsonBuildingInfo::isPower, "bool ()")
		.def("isPrereqPower", &CvJsonBuildingInfo::isPrereqPower, "bool ()")
		.def("isForceTeamVoteEligible", &CvJsonBuildingInfo::isForceTeamVoteEligible, "bool ()")
		.def("isCapital", &CvJsonBuildingInfo::isCapital, "bool ()")
		.def("isGovernmentCenter", &CvJsonBuildingInfo::isGovernmentCenter, "bool ()")
		.def("isGoldenAge", &CvJsonBuildingInfo::isGoldenAge, "bool ()")
		.def("isMapCentering", &CvJsonBuildingInfo::isMapCentering, "bool ()")
		.def("isNoUnhappiness", &CvJsonBuildingInfo::isNoUnhappiness, "bool ()")
		.def("isBuildingOnlyHealthy", &CvJsonBuildingInfo::isBuildingOnlyHealthy, "bool ()")
		.def("isNukeImmune", &CvJsonBuildingInfo::isNukeImmune, "bool ()")
		.def("isAllowsNukes", &CvJsonBuildingInfo::isAllowsNukes, "bool ()")
		.def("isRequiresActiveCivics", &CvJsonBuildingInfo::isRequiresActiveCivics, "bool ()")
		.def("isPower", &CvJsonBuildingInfo::isPower, "int ()")
		.def("isProvidesFreshWater", &CvJsonBuildingInfo::isProvidesFreshWater, "bool ()")
		.def("isAnyDomainFreeExperience", &CvJsonBuildingInfo::isAnyDomainFreeExperience, "bool ()")
		.def("isAnyLocalSpecialistYieldChanges", &CvJsonBuildingInfo::isAnyLocalSpecialistYieldChanges, "bool ()")
		.def("isAnyLocalSpecialistCommerceChanges", &CvJsonBuildingInfo::isAnyLocalSpecialistCommerceChanges, "bool ()")
		.def("isAnySpecialistYieldChanges", &CvJsonBuildingInfo::isAnySpecialistYieldChanges, "bool ()")
		.def("isAnySpecialistCommerceChanges", &CvJsonBuildingInfo::isAnySpecialistCommerceChanges, "bool ()")
		.def("isAnyBonusYieldChanges", &CvJsonBuildingInfo::isAnyBonusYieldChanges, "bool ()")
		.def("isAnyVicinityBonusYieldChanges", &CvJsonBuildingInfo::isAnyVicinityBonusYieldChanges, "bool ()")
		.def("isAnyBonusYieldModifiers", &CvJsonBuildingInfo::isAnyBonusYieldModifiers, "bool ()")
		.def("isAnyBonusCommerceModifiers", &CvJsonBuildingInfo::isAnyBonusCommerceModifiers, "bool ()")
		.def("isAnyBonusCommercePercentChanges", &CvJsonBuildingInfo::isAnyBonusCommercePercentChanges, "bool ()")

		.def("isAnyTechSpecialistChanges", &CvJsonBuildingInfo::isAnyTechSpecialistChanges, "bool ()")

		.def("getConstructSound", &CvJsonBuildingInfo::getConstructSound, "string ()")
		.def("getHotKey", &CvJsonBuildingInfo::getHotKey, "string ()")
		.def("getArtDefineTag", &CvJsonBuildingInfo::getArtDefineTag, "string ()")
		.def("getMovie", &CvJsonBuildingInfo::getMovie, "string ()")

		// Arrays

		.def("getYieldChange", &CvJsonBuildingInfo::getYieldChange, "int (int i)")
		.def("getYieldPerPopChange", &CvJsonBuildingInfo::getYieldPerPopChange, "int (int i)")

		.def("getRiverPlotYieldChange", &CvJsonBuildingInfo::getRiverPlotYieldChange, "int (int i)")
		.def("getYieldModifier", &CvJsonBuildingInfo::getYieldModifier, "int (int i)")
		.def("getPowerYieldModifier", &CvJsonBuildingInfo::getPowerYieldModifier, "int (int i)")
		.def("getAreaYieldModifier", &CvJsonBuildingInfo::getAreaYieldModifier, "int (int i)")
		.def("getGlobalYieldModifier", &CvJsonBuildingInfo::getGlobalYieldModifier, "int (int i)")
		.def("getGlobalSeaPlotYieldChange", &CvJsonBuildingInfo::getGlobalSeaPlotYieldChange, "int (int i)")
		.def("getCommerceChange", &CvJsonBuildingInfo::getCommerceChange, "int (int i)")
		.def("getCommercePerPopChange", &CvJsonBuildingInfo::getCommercePerPopChange, "int (int i)")
		.def("getCommerceModifier", &CvJsonBuildingInfo::getCommerceModifier, "int (int i)")
		.def("getGlobalCommerceModifier", &CvJsonBuildingInfo::getGlobalCommerceModifier, "int (int i)")
		.def("getCommerceHappiness", &CvJsonBuildingInfo::getCommerceHappiness, "int (int i)")
		.def("getCommerceChangeDoubleTime", &CvJsonBuildingInfo::getCommerceChangeDoubleTime, "int (int i)")
		.def("getSpecialistExtraCommerce", &CvJsonBuildingInfo::getSpecialistExtraCommerce, "int (int i)")
		.def("getSpecialistCount", &CvJsonBuildingInfo::getSpecialistCount, "int (int i)")
		.def("getFreeSpecialistCount", &CvJsonBuildingInfo::getFreeSpecialistCount, "int (int i)")
		.def("getDomainFreeExperience", &CvJsonBuildingInfo::getDomainFreeExperience, "int (int i)")
		.def("getUnitCombatFreeExperience", &CvJsonBuildingInfo::getUnitCombatFreeExperience, python::return_value_policy<python::reference_existing_object>())
		.def("getHealUnitCombatType", &CvJsonBuildingInfo::getHealUnitCombatType, python::return_value_policy<python::reference_existing_object>(), "int (int i)")
		.def("getNumHealUnitCombatTypes", &CvJsonBuildingInfo::getNumHealUnitCombatTypes, "int ()")
		.def("getDomainProductionModifier", &CvJsonBuildingInfo::getDomainProductionModifier, "int (int i)")
		.def("getUnitCombatExtraStrength", &CvJsonBuildingInfo::getUnitCombatExtraStrength, python::return_value_policy<python::reference_existing_object>())
		.def("getUnitCombatProdModifier", &CvJsonBuildingInfo::getUnitCombatProdModifier, "int (int i)")
		.def("getPrereqAndTechs", &CvJsonBuildingInfo::getPrereqAndTechs, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqOrBonuses", &CvJsonBuildingInfo::getPrereqOrBonuses, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqOrHeritage", &CvJsonBuildingInfo::getPrereqOrHeritage, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqOrVicinityBonuses", &CvJsonBuildingInfo::getPrereqOrVicinityBonuses, python::return_value_policy<python::reference_existing_object>())
		.def("getPrereqOrRawVicinityBonuses", &CvJsonBuildingInfo::getPrereqOrRawVicinityBonuses, python::return_value_policy<python::reference_existing_object>())
		.def("getTechHappinessChanges", &CvJsonBuildingInfo::getTechHappinessChanges, python::return_value_policy<python::reference_existing_object>())
		.def("getTechHealthChanges", &CvJsonBuildingInfo::getTechHealthChanges, python::return_value_policy<python::reference_existing_object>())
		.def("getTechYieldChanges100", &CvJsonBuildingInfo::cyGetTechYieldChanges100)
		.def("getTechYieldModifiers", &CvJsonBuildingInfo::cyGetTechYieldModifiers)
		.def("getTechCommerceChanges100", &CvJsonBuildingInfo::cyGetTechCommerceChanges100)
		.def("getTechCommerceModifiers", &CvJsonBuildingInfo::cyGetTechCommerceModifiers)
		.def("getTechSpecialistChange", &CvJsonBuildingInfo::getTechSpecialistChange, "int (int i, int j)")
		.def("getLocalSpecialistCommerceChange", &CvJsonBuildingInfo::getLocalSpecialistCommerceChange, "int (int i, int j)")
		.def("getSpecialistCommerceChange", &CvJsonBuildingInfo::getSpecialistCommerceChange, "int (int i, int j)")
		.def("getSpecialistYieldChange", &CvJsonBuildingInfo::getSpecialistYieldChange, "int (int i, int j)")
		.def("getTerrainYieldChange", &CvJsonBuildingInfo::cyGetTerrainYieldChanges)
		.def("getPlotYieldChange", &CvJsonBuildingInfo::cyGetPlotYieldChanges)
		.def("getImprovementYieldChange", &CvJsonBuildingInfo::cyGetImprovementYieldChanges)
		.def("getGlobalImprovementYieldChange", &CvJsonBuildingInfo::cyGetGlobalImprovementYieldChanges)
		.def("getFreePromoTypes", &CvJsonBuildingInfo::cyGetFreePromoTypes)

		.def("getBonusYieldChanges", &CvJsonBuildingInfo::getBonusYieldChanges, "int (int i, int j)")
		.def("getBonusYieldModifier", &CvJsonBuildingInfo::getBonusYieldModifier, "int (int i, int j)")
		.def("getVicinityBonusYieldChanges", &CvJsonBuildingInfo::getVicinityBonusYieldChanges, "int (int i, int j)")
		.def("getBonusCommerceModifier", &CvJsonBuildingInfo::getBonusCommerceModifier, "int (int i, int j)")
		.def("getBonusCommercePercentChanges", &CvJsonBuildingInfo::getBonusCommercePercentChanges, "int (int i, int j)")
		.def("getBonusHealthChanges", &CvJsonBuildingInfo::getBonusHealthChanges, python::return_value_policy<python::reference_existing_object>())
		.def("getBonusHappinessChanges", &CvJsonBuildingInfo::getBonusHappinessChanges, python::return_value_policy<python::reference_existing_object>())
		.def("getBonusProductionModifier", &CvJsonBuildingInfo::getBonusProductionModifier, "int (int i)")
		.def("getBonusDefenseChanges", &CvJsonBuildingInfo::getBonusDefenseChanges, "int (int i)")

		.def("getPrereqNumOfBuildings", &CvJsonBuildingInfo::getPrereqNumOfBuildings, python::return_value_policy<python::reference_existing_object>())
		.def("getFlavorValue", &CvJsonBuildingInfo::getFlavorValue, "int (int i)")
		.def("getImprovementFreeSpecialists", &CvJsonBuildingInfo::getImprovementFreeSpecialists, python::return_value_policy<python::reference_existing_object>())

		.def("getGlobalBuildingCostModifiers", &CvJsonBuildingInfo::getGlobalBuildingCostModifiers, python::return_value_policy<python::reference_existing_object>())
		.def("getGlobalBuildingCommerceChanges", &CvJsonBuildingInfo::cyGetGlobalBuildingCommerceChanges)
		.def("getGlobalBuildingProductionModifiers", &CvJsonBuildingInfo::getGlobalBuildingProductionModifiers, python::return_value_policy<python::reference_existing_object>())
		.def("getBuildingHappinessChanges", &CvJsonBuildingInfo::getBuildingHappinessChanges, python::return_value_policy<python::reference_existing_object>())
		.def("getBuildingProductionModifiers", &CvJsonBuildingInfo::getBuildingProductionModifiers, python::return_value_policy<python::reference_existing_object>())
		.def("getUnitProductionModifiers", &CvJsonBuildingInfo::getUnitProductionModifiers, python::return_value_policy<python::reference_existing_object>())
		.def("getExtendsBuilding", &CvJsonBuildingInfo::getExtendsBuilding, "int ()")
		.def("getPrereqNotInCityBuilding", &CvJsonBuildingInfo::getPrereqNotInCityBuilding, "int (int i)")
		.def("getNumPrereqNotInCityBuildings", &CvJsonBuildingInfo::getNumPrereqNotInCityBuildings, "short ()")

		.def("isPrereqOrCivics", &CvJsonBuildingInfo::isPrereqOrCivics, "bool (int i)")
		.def("isPrereqAndCivics", &CvJsonBuildingInfo::isPrereqAndCivics, "bool (int i)")

		.def("isPrereqOrTerrain", &CvJsonBuildingInfo::isPrereqOrTerrain, "bool (int i)")
		.def("isPrereqAndTerrain", &CvJsonBuildingInfo::isPrereqAndTerrain, "bool (int i)")

		.def("getPrereqOrImprovements", &CvJsonBuildingInfo::getPrereqOrImprovements, python::return_value_policy<python::reference_existing_object>())
		.def("isPrereqOrFeature", &CvJsonBuildingInfo::isPrereqOrFeature, "bool (int i)")

		.def("getPrereqOrBuilding", &CvJsonBuildingInfo::getPrereqOrBuilding, "int (int i)")
		.def("getNumPrereqOrBuilding", &CvJsonBuildingInfo::getNumPrereqOrBuilding, "short ()")
		.def("isPrereqOrBuilding", &CvJsonBuildingInfo::isPrereqOrBuilding, "bool (int i)")

		.def("getReplacementBuilding", &CvJsonBuildingInfo::getReplacementBuilding, "int (int i)")
		.def("getNumReplacementBuilding", &CvJsonBuildingInfo::getNumReplacementBuilding, "short ()")
		.def("getReplacedBuilding", &CvJsonBuildingInfo::getReplacedBuilding, "int (int i)")
		.def("getNumReplacedBuilding", &CvJsonBuildingInfo::getNumReplacedBuilding, "short ()")

		.def("getNumPopulationEmployed", &CvJsonBuildingInfo::getNumPopulationEmployed, "int")

		.def("isCommerceFlexible", &CvJsonBuildingInfo::isCommerceFlexible, "bool (int i)")

		.def("getPrereqInCityBuilding", &CvJsonBuildingInfo::getPrereqInCityBuilding, "int (int i)")
		.def("getNumPrereqInCityBuildings", &CvJsonBuildingInfo::getNumPrereqInCityBuildings, "short ()")
		.def("isPrereqInCityBuilding", &CvJsonBuildingInfo::isPrereqInCityBuilding, "bool (int i)")

		.def("getMapCategories", &CvJsonBuildingInfo::getMapCategories, python::return_value_policy<python::reference_existing_object>())

		.def("getProperties", &CvJsonBuildingInfo::getProperties, python::return_value_policy<python::reference_existing_object>(), "CvProperties ()")
		.def("getPropertyManipulators", &CvJsonBuildingInfo::getPropertyManipulators, python::return_value_policy<python::reference_existing_object>())

		.def("getConstructCondition", &CvJsonBuildingInfo::getConstructCondition, python::return_value_policy<python::reference_existing_object>())
		;

	python::class_<CvSpecialBuildingInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvSpecialBuildingInfo", python::no_init)
		.def("getObsoleteTech", &CvSpecialBuildingInfo::getObsoleteTech, "int ()")
		.def("getTechPrereq", &CvSpecialBuildingInfo::getTechPrereq, "int ()")
		.def("isValid", &CvSpecialBuildingInfo::isValid, "bool ()")
		;

	python::class_<CvJsonPromotionLineInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvPromotionLineInfo", python::no_init)
		.def("getPrereqTech", &CvJsonPromotionLineInfo::getPrereqTech, "int ()")
		.def("getObsoleteTech", &CvJsonPromotionLineInfo::getObsoleteTech, "int ()")
		.def("isBuildUp", &CvJsonPromotionLineInfo::isBuildUp, "bool ()")
		;

	python::class_<CvJsonUnitCombatInfo, python::bases<CvInfoBase>, boost::noncopyable>("CvUnitCombatInfo", python::no_init)
		.def("getVisibilityChange", &CvJsonUnitCombatInfo::getVisibilityChange, "int ()")
		.def("getMoveDiscountChange", &CvJsonUnitCombatInfo::getMoveDiscountChange, "int ()")
		.def("getWithdrawalChange", &CvJsonUnitCombatInfo::getWithdrawalChange, "int ()")
		.def("getCollateralDamageChange", &CvJsonUnitCombatInfo::getCollateralDamageChange, "int ()")
		.def("getFirstStrikesChange", &CvJsonUnitCombatInfo::getFirstStrikesChange, "int ()")
		.def("getChanceFirstStrikesChange", &CvJsonUnitCombatInfo::getChanceFirstStrikesChange, "int ()")
		.def("getEnemyHealChange", &CvJsonUnitCombatInfo::getEnemyHealChange, "int ()")
		.def("getNeutralHealChange", &CvJsonUnitCombatInfo::getNeutralHealChange, "int ()")
		.def("getFriendlyHealChange", &CvJsonUnitCombatInfo::getFriendlyHealChange, "int ()")
		.def("getCombatPercent", &CvJsonUnitCombatInfo::getCombatPercent, "int ()")
		.def("getCityAttackPercent", &CvJsonUnitCombatInfo::getCityAttackPercent, "int ()")
		.def("getCityDefensePercent", &CvJsonUnitCombatInfo::getCityDefensePercent, "int ()")
		.def("getHillsDefensePercent", &CvJsonUnitCombatInfo::getHillsDefensePercent, "int ()")
		.def("getRevoltProtection", &CvJsonUnitCombatInfo::getRevoltProtection, "int ()")
		.def("getPillageChange", &CvJsonUnitCombatInfo::getPillageChange, "int ()")
		.def("getUpgradeDiscount", &CvJsonUnitCombatInfo::getUpgradeDiscount, "int ()")
		.def("getStrengthModifier", &CvJsonUnitCombatInfo::getStrengthModifier, "int ()")
		.def("isRiver", &CvJsonUnitCombatInfo::isRiver, "bool ()")
		;
}
