name: Commit jobs
on: [push, pull_request]
jobs:
  validate-xmls:
    name: Validate XMLs
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run XmlValidator
        working-directory: ${{ github.workspace }}/Tools
        run: |
          ${{ github.workspace }}/Tools/XmlValidator.exe -a
